server:
  port: 8085

spring:
  application:
    name: exception-service

  # Настройки подключения к БД
  datasource:
    url: jdbc:postgresql://exception-db:5432/exception_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  # Настройки JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update # Автоматически создаст таблицы при запуске
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
