server:
  port: 8761

eureka:
  instance:
    # Имя должно СТРОГО совпадать с названием сервиса в docker-compose.yml
    hostname: eureka-server 
    # Для СЕРВЕРА в докере лучше false, чтобы он использовал hostname для ссылок
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # Ссылаемся на самого себя по правильному имени
      defaultZone: http://eureka-server:8761/eureka/