spring:
  application:
    name: hello-service

server:
  port: 0 # Случайный порт

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # Генерируем уникальный ID, чтобы видеть разные запущенные копии
     instance-id: ${spring.application.name}:${random.value}
     prefer-ip-address: true