server:
  port: 8080

spring:
  application:
    name: b9-gateway-service
  config:
    import: "vault://"
  cloud:
    gateway:
      routes:
        - id: hello_world_route
          uri: lb://HELLO-SERVICE  # Должно быть в точности как в Dashboard Эврики!
          predicates:
            - Path=/hello/**
          filters:
            - AuthenticationFilter
        - id: auth_service_route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
    vault:
      uri: http://vault:8200
      authentication: TOKEN
      token: ${SPRING_CLOUD_VAULT_TOKEN:my-root-token-qwerty12345}
      kv:
        enabled: true
        backend: secret
        default-context: application

jwt:
  # Просто строка-заглушка. Vault заменит её автоматически при старте.
  secret: "placeholder_key_gateway_32_chars_long"

eureka:
  client:
    service-url:
      # Имя должно строго совпадать с именем в docker-compose!
      defaultZone: http://eureka-server:8761/eureka/