server:
  port: 8080

spring:
  application:
    name: b9-gateway-service
  cloud:
    gateway:
      routes:
        # Маршрут для Hello Service
        - id: hello_world_route
          uri: lb://hello-service
          predicates:
            - Path=/hello/**

        # НОВЫЙ маршрут для Auth Service
        - id: auth_service_route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://eureka-server:8761/eureka/