server:
  port: 8080

spring:
  application:
    name: b9-gateway-service
  config:
    import: "vault://"
  cloud:
    gateway:
      routes:
        # Маршрут для сервиса исключений (Диагностика)
        - id: exception_service_route
          uri: lb://EXCEPTION-SERVICE # Имя из Eureka
          predicates:
            - Path=/exception/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter

        - id: hello_world_route
          uri: lb://HELLO-SERVICE
          predicates:
            - Path=/hello/**
          filters:
            - AuthenticationFilter
            
        - id: auth_service_route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

      default-filters:
        - PreserveHostHeader
    vault:
      uri: http://vault:8200
      authentication: TOKEN
      token: ${SPRING_CLOUD_VAULT_TOKEN:my-root-token-qwerty12345}
      kv:
        enabled: true
        backend: secret
        default-context: application

jwt:
  secret: "placeholder_key_gateway_32_chars_long"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/