server:
  port: 8080

spring:
  application:
    name: b9-gateway-service
  cloud:
    gateway:
      routes:
        - id: hello_world_route
          uri: lb://hello-service
          # uri: http://localhost:8083
          predicates:
            - Path=/hello/**

eureka:
    client:
      registry-fetch-interval-seconds: 5 # Спрашивать список каждые 5 сек
      service-url:
        defaultZone: http://localhost:8761/eureka/